const test = require('node:test');
const assert = require('node:assert/strict');
const sharp = require('sharp');
const postcss = require('postcss');
const { optimizeImage, detectContentType } = require('next/dist/server/image-optimizer');

test('patched Sharp supports the actual Next image optimizer for every output format', async () => {
  const input = await sharp({
    create: { width: 32, height: 24, channels: 4, background: '#2486cb' },
  }).png().toBuffer();
  for (const format of ['png', 'jpeg', 'webp', 'avif']) {
    const output = await optimizeImage({
      buffer: input, contentType: `image/${format}`, quality: 75, width: 16,
    });
    const metadata = await sharp(output).metadata();
    assert.equal(await detectContentType(output), `image/${format}`);
    // Sharp reports AVIF's HEIF container, with AV1 compression.
    assert.equal(metadata.format, format === 'avif' ? 'heif' : format);
    if (format === 'avif') assert.equal(metadata.compression, 'av1');
    assert.equal(metadata.width, 16);
    assert.equal(metadata.height, 12);
    // Decode generated bytes too: metadata alone does not prove readable output.
    const decoded = await sharp(output).raw().toBuffer();
    assert.ok(decoded.length >= 16 * 12 * 3);
  }
});

test('patched PostCSS retains parsing and plugin transforms used by CSS builds', async () => {
  const result = await postcss([{
    postcssPlugin: 'dependency-compatibility-smoke',
    Declaration(declaration) {
      if (declaration.prop === 'color') declaration.value = '#2486cb';
    },
  }]).process(':root { --brand: #fff } .room { color: var(--brand); margin: 0 }', {
    from: undefined, map: false,
  });
  const declarations = [];
  postcss.parse(result.css).walkDecls(declaration => declarations.push([declaration.prop, declaration.value.trim()]));
  assert.deepEqual(declarations, [['--brand', '#fff'], ['color', '#2486cb'], ['margin', '0']]);
});
